name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install modules
        run: make install

      - name: Run ESLint
        run: make lint
